name: Publish to NuGet
on:
  push:
    tags:
      - 'v*'    # triggers on tags like v2.1.0, v2.2.0, v3.0.0
jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.x'
      - name: Remove Database Project
        run: rm -rf EFConvention.Database
      - name: Restore
        run: |
          dotnet restore EFConvention/EFConvention.csproj
          dotnet restore EFConvention.Sample/EFConvention.Sample.csproj
          dotnet restore EFConvention.Tests/EFConvention.Tests.csproj
      - name: Build
        run: |
          dotnet build EFConvention/EFConvention.csproj --configuration Release --no-restore
          dotnet build EFConvention.Sample/EFConvention.Sample.csproj --configuration Release --no-restore
          dotnet build EFConvention.Tests/EFConvention.Tests.csproj --configuration Release --no-restore
      - name: Test
        run: dotnet test EFConvention.Tests/EFConvention.Tests.csproj --configuration Release --no-build
      - name: Pack
        run: dotnet pack EFConvention/EFConvention.csproj --configuration Release --no-build --output ./nupkg
      - name: Push to NuGet.org
        run: dotnet nuget push ./nupkg/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
